version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - SERIAL_PORT=/dev/ttyUSB0
    volumes:
      - ./api:/app
    depends_on:
      - mosquitto
    restart: unless-stopped

  bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - SERIAL_PORT=/dev/ttyUSB0
    volumes:
      - ./bridge:/app
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - api
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: 